### ISSUE TITLE
Doesn't work with nested tags

### ISSUE THREAD

**Issue by kmaustral** [code-of-chaos/obsidian-colored_tags_wrangler#33]
This plugin works well with single tags, but most of my tags are nested. These remain plain after customising in the plugin.

**Comment by AnnaSasDev** [comment]
with nested tags, do you mean `#tag-1/nested-tag` ?
This is currently planned on being added, but will be an optional feature, because it'll most likely require more than simple CSS

**Comment by kmaustral** [comment]
Yes, that's right. I've un-nested some key tags for the moment that I want to use. But I imagine they'll want to return to the next one day.

**Comment by AnnaSasDev** [comment]
A current workaround would be using the "Enable Multiple Tags per line option" (like the image below) and writing something like `tag-1;tag-1/nested-tag` on the same line.
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/dccc1a9b-4f72-4828-b7cd-4356fd6f7fa7)

(below is an image of how I've used the multiple tags per line)
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/eda3c3df-5463-4569-a301-d147f8e277b8)

It isn't a perfect solution for the "nested tags" issue, but it should help you along. Hope it works

**Comment by AnnaSasDev** [comment]
Uhm, just tested it our myself and there is a small bug with the "/" in tags. Am working on a hotfix for it as I type

**Comment by AnnaSasDev** [comment]
The `/` not being able to be used in tags should be fixed through PR #34 and is released in `0.16.3`
Sorry for the inconvenience @kmaustral

**Comment by kmaustral** [comment]
Briliant! That's quick work.

_______
Melbourne, Narrm, Australia
📅 Thursday, 04 January 02024
Biderap 🦋 (tussock grass) season with brown butterflies
🌓 Last quarter
🌡️ Cloudy. Medium chance of morning drizzle. Winds south to southwesterly
15 to 20 km/h tending south to southeasterly 15 to 25 km/h during the
afternoon and evening. 24º
🌏 Current CO2 is 422.33 ppm (last year 419.1 ppm).

**Comment by AnnaSasDev** [comment]
in the latest `0.17.5` update, all issues with tags having a `/` should have been resolved. Currently I  don't see an easy way to automatically color nested tags. Though this could theoretically be done with JQuery, the lookups would have to be done every time the note is changed, which will impact performance too much.
Currently the intended way would be to simply define these nested tags once, manually, in the settings. This way it can be resolved through plain CSS

**Comment by mattie152** [comment]
Forgive me for commenting on a closed issue, I was just checking whether anyone had already contributed this since I was about to.

I had a look at the plugin code but it's definitely way above my level. But I did solve the nested tags issue with a [pretty simple css snippet](https://www.reddit.com/r/ObsidianMD/comments/1b9l60s/css_snippet_for_coloured_tags_in_reading_and/). Maybe something like this would work?

**Comment by AnnaSasDev** [comment]
No worries @mattie152 for commenting on this issue.
The "problem" with tags in Obsidian and my plugin, is that within Obsidian the HTML for each tag isn't created in the same manner. Some implementations of tags take the `/` into account, the other ones remove it or replace it with a "-".
Then within my own plugin (which needs a rewrite, due to this and some other issues) wasn't built with nested tags in mind, so my solution, although working, isn't the best it can be either.

For the rewrite I'll surely take your snippet into account.
