### ISSUE TITLE
Issues with coloring tags in properties

### ISSUE THREAD

**Issue by vorrermid** [code-of-chaos/obsidian-colored_tags_wrangler#35]
1. Background opacity in properties doesn't work.
2. Color is reset when adding or removing a tag from properties.
Is that fixable?
![dfdf](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/135044823/08239c2b-8473-4a0f-ae69-93dc904f90a3)

**Comment by AnnaSasDev** [comment]
thanks for the descriptive gif! 
1. That is a bug and will be fixed asap
2. Properties don't have a decent API yet and makes things a little bit more difficult. The reloading issue should have been fixed in version 0.16.3.

**Comment by AnnaSasDev** [comment]
The transparency has been fixed in version 0.16.4, and the tags not coloring correctly on a change in the properties should have been fixed in 0.16.3 normally already. Please make sure you are on the latest release :D

**Comment by vorrermid** [comment]
Wow! That was fast! 😮
Transparency tags in properties work in version 0.16.5. Thank you very much! 
But the bug of colors when changing properties, do not work in 0.16.3 and 0.16.5. Although it is not so important for me, the main thing was the transparency of tags in properties.

**Comment by vorrermid** [comment]
https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/135044823/548d3252-ad25-4fc3-803f-dac3981d1f97

**Comment by AnnaSasDev** [comment]
can you confirm that this is still an issue in the latest version, 0.17.1?

**Comment by vorrermid** [comment]
> can you confirm that this is still an issue in the latest version, 0.17.1?

Yes. The problem exists in all recent versions 0.17.0-0.17.2.

---

In new versions starting from 0.17.0 there is a problem with background transparency.
![bug](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/135044823/c4272b9d-7518-4cf0-895b-e04f66a4c81f)

**Comment by vorrermid** [comment]
Do you have these bugs or is it just me?

**Comment by AnnaSasDev** [comment]
Okay, I think I finally understand what has happend (on my end)
I reworked the color selection and retrieval system, remove the Luminance system which was making certain colors appear different than they were assigned. In the process, I reworked how the opacity was applied to items.
In the latest version they apply to elements other than the original tags ...
The setting's text is confusing and should be changed. In the process I'll expand the setting and make it so that users can define them on a per section basis (example: If you want to enable transparency for Canvas but not for Folder Notes)
